name = "AstroForceModels"
uuid = "077569d7-e100-45f3-83e3-c646e23345bd"
authors = ["Jordan Murphy <jmurphy6895@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
