name = "AstroForceModels"
uuid = "077569d7-e100-45f3-83e3-c646e23345bd"
authors = ["Jordan Murphy <jmurphy6895@gmail.com> and contributors"]
version = "0.1.0"

[deps]
AngleBetweenVectors = "ec570357-d46e-52ed-9726-18773498274d"
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
SatelliteToolboxAtmosphericModels = "5718ef0a-a30f-426d-bcd9-4cf31dd12909"
SatelliteToolboxBase = "9e17983a-0463-41a7-9a16-1682db6d8b66"
SatelliteToolboxCelestialBodies = "b0edd99f-a7ca-4aa6-9a1e-a53e8f506046"
SatelliteToolboxGravityModels = "bd9e9728-6f7b-4d28-9e50-c765cb1b7c8c"
SatelliteToolboxTransformations = "6b019ec1-7a1e-4f04-96c7-a9db1ca5514d"
SpaceIndices = "5a540a4e-639f-452a-b107-23ea09ed4d36"
StaticArraysCore = "1e83bf80-4336-4d27-bf5d-d5a4f845583c"

[compat]
AngleBetweenVectors = "0.3"
Aqua = "0.8"
ComponentArrays = "0.15"
LinearAlgebra = "1"
Parameters = "0.12"
SatelliteToolboxAtmosphericModels = "0.1"
SatelliteToolboxBase = "0.3"
SatelliteToolboxCelestialBodies = "0.1"
SatelliteToolboxGravityModels = "0.1"
SatelliteToolboxTransformations = "0.1"
SpaceIndices = "1"
StaticArraysCore = "1"
Test = "1"
julia = "1.9"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["AllocCheck", "Aqua", "Test"]
